### ISSUE TITLE
SCSS/CSS missing in npm package

### ISSUE THREAD

**Issue by hummal** [nawafscript/toaststrap#2]
First of all -> Thank you for your effort. I was thinking of exaclty the same problem and you already solved it for me. Nice.

But using it without having the css to display anything is not possible. The package does not contain the "dist" folder. You should consider setting up the package.json to include the dist folder in released. 

I guess you will be fast in resolving this issue without any PR needed.

**Comment by nawafscript** [comment]
Hi @hummal ,
 
I will fix that tomorrow. Thanks.

**Comment by nawafscript** [comment]
Hello, @hummal 
This issue has been fixed in version 1.1.0 .

You can now import the compiled CSS.
`@import "~toaststrap/bundle/toaststrap.css"`
OR
`@import url("node_modules/toaststrap/bundle/toaststrap.css`

Thanks for reporting.
