### ISSUE TITLE
Wrong CSS Classes on element

### ISSUE THREAD

**Issue by hummal** [nawafscript/toaststrap#3]
NPM Package does not provide correct classes. 

`position-fixed toastsrap-bottom toastsrap-end-5 toastsrap-container show`

There is a type in all of them "toastsrap" > "toaststrap"

**Comment by nawafscript** [comment]
> NPM Package does not provide correct classes.
> 
> `position-fixed toastsrap-bottom toastsrap-end-5 toastsrap-container show`
> 
> There is a type in all of them "toastsrap" > "toaststrap"

Thank you for reporting the issue.
I already working on a new version which have many fixes, I'll fix that too.

**Comment by nawafscript** [comment]
The issue has been fixed in version 1.1.0.
Thank you for reporting.
